name: Unit Tests
on: [push, pull_request]

jobs:
  TestsExecution:
    runs-on: ubuntu-latest
    container: arthichaud/ci_docker_image:latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Compile
        run: make
      - name: Exec Unit Tests
        run: make tests_run
      - name: Get Unit Tests trace
        if: ${{ always() }}
        run: ./unit_tests --ascii 2> unit_tests_trace.txt
      - name: Upload Unit Tests trace
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: unit_tests_trace
          path: unit_tests_trace.txt
      - name: Upload coverage files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage_files
          path: ./*.gc*
  UploadCoverage:
    needs:  TestsExecution
    if: ${{ always() }}
    runs-on: ubuntu-latest
    container: arthichaud/ci_docker_image:latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Download coverage files from previous job
        uses: actions/download-artifact@v2
        with:
          name: coverage_files
      - name: Get coverage
        run: make coverage > coverage.txt
      - name: Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.txt
